[package]
name = "dixon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rug = "1.15.0"
types = { path = "../types" }
algorithms = { path = "../algorithms" }
nalgebra = "0.30.1"
